<?xml version="1.0"?>
<package format="3">
  <name>sound_play_pkg</name>
  <version>0.1.0</version>
  <description>Play local wav/mp3 by UInt8 message</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>ament_index_cpp</build_depend>
  <build_depend>tier4_planning_msgs</build_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>ament_index_cpp</exec_depend>
  <exec_depend>tier4_planning_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
